#!/bin/bash
set -e

SUFFIX=$(date +%Y%m%d%H%M%S)
DEVELOPER_NAME=$USER$SUFFIX
AZURE_SUBSCRIPTION_ID=$1
AZURE_RESOURCE_GROUP=$2
AZURE_SCOPES="/subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$AZURE_RESOURCE_GROUP"

function usage () {
    echo "Usage: $0 -s <subscription-id> -g <resource-group>"
    exit 1
}

while getopts s:g: OPT
do
    case $OPT in
        s) AZURE_SUBSCRIPTION_ID=$OPTARG
            ;;
        g) AZURE_RESOURCE_GROUP=$OPTARG
            ;;
        *) usage
            ;;
    esac
done

if [ -z "$AZURE_SUBSCRIPTION_ID" ]; then
    usage
fi

if [ -z "$AZURE_RESOURCE_GROUP" ]; then
    usage
fi

# memo: https://docs.microsoft.com/ja-jp/azure/role-based-access-control/built-in-roles
# "Storage Blob Data Owner"
# "Storage Account Contributor"
roles=(
    "b7e6dc6d-f1e8-4753-8033-0f276bb0955b"
    "17d1049b-9a84-46fb-8f53-869881c3d3ab"
)

echo "AZURE_SCOPES=$AZURE_SCOPES"
echo "roles=${roles[@]}"
echo "AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID"
echo "AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP"
echo "DEVELOPER_NAME=$DEVELOPER_NAME"

echo "az ad sp create-for-rbac --name $DEVELOPER_NAME --json-auth"
az ad sp create-for-rbac --name $DEVELOPER_NAME --json-auth

AZURE_PRINCIPAL_ID=$(az ad sp list --display-name $DEVELOPER_NAME --output tsv --query '[].id')
AZURE_CLIENT_ID=$(az ad sp list --display-name $DEVELOPER_NAME --output tsv --query '[].appId')

for role in "${roles[@]}"; do
    echo "az role assignment create --role $role --assignee-object-id $AZURE_PRINCIPAL_ID --scope $AZURE_SCOPES --assignee-principal-type ServicePrincipal"
    az role assignment create \
        --role $role \
        --assignee-object-id $AZURE_PRINCIPAL_ID \
        --scope $AZURE_SCOPES \
        --assignee-principal-type ServicePrincipal
done
