#!/bin/bash
set -eu

SUFFIX=$(date +%Y%m%d%H%M%S)
RESOURCE_GROUP="blobapp"-$SUFFIX
ENVIRONMENT="env-blobapps"-$SUFFIX
API_NAME="blobapp"-$SUFFIX
ACR_NAME="acrblobapp"$SUFFIX
STORAGE_NAME="blobapp"$SUFFIX
LOCATION="japaneast"
SUBSCRIPTION="<SUBSCRIPTION>"
IDENTITY="blobappIdentity"$SUFFIX # for user-assigned identity

az account set --subscription $SUBSCRIPTION
az login

az extension add --name containerapp --upgrade
az provider register --namespace Microsoft.App
az provider register --namespace Microsoft.OperationalInsights

# Create Resource Group
az group create \
  --name $RESOURCE_GROUP \
  --location $LOCATION

# Create user assigned identity
az identity create \
  --name $IDENTITY \
  --resource-group $RESOURCE_GROUP

# Get user assigned identity id
IDENTITY_ID=$(az identity show \
 --name $IDENTITY \
 --resource-group $RESOURCE_GROUP \
 --query id \
 --output json| sed -e 's/^"//' -e 's/"$//')

# Get user assigned identity principal id
PRINCIPAL_ID=$(az identity show \
  --name $IDENTITY \
  --resource-group $RESOURCE_GROUP \
  --query principalId \
  --output json | sed -e 's/^"//' -e 's/"$//')

# Create Container Registry
az acr create \
  --resource-group $RESOURCE_GROUP \
  --name $ACR_NAME \
  --sku Basic \
  --admin-enabled true

# Assign user assigned identity to container registry
az acr identity assign \
  --name $ACR_NAME \
  --resource-group $RESOURCE_GROUP \
  --identities $IDENTITY_ID

# Get container registry id
ACR_ID=$(az acr show \
 --name $ACR_NAME \
 --query id \
 --output json | sed -e 's/^"//' -e 's/"$//')

# Assign role to user assigned identity
az role assignment create \
 --assignee $PRINCIPAL_ID \
 --role AcrPull \
 --scope $ACR_ID

# build and push image
docker build --tag $ACR_NAME.azurecr.io/$API_NAME .
az acr login --name $ACR_NAME
docker push $ACR_NAME.azurecr.io/$API_NAME

# Create Storage Account Azure Data Lake Storage Gen2
az storage account create \
  --name $STORAGE_NAME \
  --resource-group $RESOURCE_GROUP \
  --location "$LOCATION" \
  --sku Premium_LRS \
  --kind BlockBlobStorage \
  --enable-hierarchical-namespace true

STORAGE_ACCOUNT_ID=$(az storage account show \
  --resource-group $RESOURCE_GROUP \
  --name $STORAGE_NAME \
  --query id \
  --output json | sed -e 's/^"//' -e 's/"$//')

az role assignment create \
  --assignee $PRINCIPAL_ID \
  --role "Storage Blob Data Contributor" \
  --scope $STORAGE_ACCOUNT_ID

# Create Environment for Container App
az containerapp env create \
  --name $ENVIRONMENT \
  --resource-group $RESOURCE_GROUP \
  --location $LOCATION

# Create container app
az containerapp create \
  --name $API_NAME \
  --resource-group $RESOURCE_GROUP \
  --environment $ENVIRONMENT \
  --registry-identity $IDENTITY_ID \
  --registry-server "$ACR_NAME.azurecr.io" \
  --target-port 1323 \
  --ingress external \
  --image "$ACR_NAME.azurecr.io/$API_NAME:latest"

# Add env in a container app
az containerapp update \
  --name $API_NAME \
  --resource-group $RESOURCE_GROUP \
  --set-env-vars AZURE_STORAGE_ACCOUNT_NAME=$STORAGE_NAME

# Assign user assigned identity to container app
az containerapp identity assign \
  --resource-group $RESOURCE_GROUP \
  --name $API_NAME \
  --user-assigned $IDENTITY_ID

# Assign system-assigned identity
# echo "(preview) system-assigned identity is not supported yet and can setup only azure portal"
# echo "Azure Portal > Container Apps > $API_NAME > Settings > Identity > System Assigned > Status > On > Assigned Principal ID > Save"
